spring:
  datasource:
    url: r2dbc:mariadb://localhost:3306/notification
    username: user
    password: password

  flyway:
    enabled: true
    url: jdbc:mariadb://localhost:3306/notification
    user: user
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true
